// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAovntlxGRvKrSv7nutcZecjQSVXz31YcA',
    appId: '1:680256798250:web:0f04581ebdb88a9e158d53',
    messagingSenderId: '680256798250',
    projectId: 'insta-c37dc',
    authDomain: 'insta-c37dc.firebaseapp.com',
    storageBucket: 'insta-c37dc.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZR_8G28gvg_TO6bjWUpZ9yKe_6ZG6BEg',
    appId: '1:680256798250:android:a03de7bf346b4560158d53',
    messagingSenderId: '680256798250',
    projectId: 'insta-c37dc',
    storageBucket: 'insta-c37dc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUT-xFHCeYGLIQ8Xdh-WCWGZpH-ss3na8',
    appId: '1:680256798250:ios:982dba15983ac514158d53',
    messagingSenderId: '680256798250',
    projectId: 'insta-c37dc',
    storageBucket: 'insta-c37dc.firebasestorage.app',
    iosBundleId: 'com.Faizz.insta',
  );
}
